nba_mvp_list = [
    {"year": 2001, "player": "Allen Iverson"},
    {"year": 2002, "player": "Tim Duncan"},
    {"year": 2003, "player": "Tim Duncan"},
    {"year": 2004, "player": "Kevin Garnett"},
    {"year": 2005, "player": "Steve Nash"},
    {"year": 2006, "player": "Steve Nash"},
    {"year": 2007, "player": "Dirk Nowitzki"},
    {"year": 2008, "player": "Kobe Bryant"},
    {"year": 2009, "player": "LeBron James"},
    {"year": 2010, "player": "LeBron James"},
    {"year": 2011, "player": "Derrick Rose"},
    {"year": 2012, "player": "LeBron James"},
    {"year": 2013, "player": "LeBron James"},
    {"year": 2014, "player": "Kevin Durant"},
    {"year": 2015, "player": "Stephen Curry"},
    {"year": 2016, "player": "Stephen Curry"},
    {"year": 2017, "player": "Russell Westbrook"},
    {"year": 2018, "player": "James Harden"},
    {"year": 2019, "player": "Giannis Antetokounmpo"},
    {"year": 2020, "player": "Giannis Antetokounmpo"},
    {"year": 2021, "player": "Nikola Jokić"},
    {"year": 2022, "player": "Nikola Jokić"},
    {"year": 2023, "player": "Joel Embiid"},
    {"year": 2024, "player": "Nikola Jokić"}
]
